### PR TITLE
Add ability to assign ticket to a user

### PR DESCRIPTION
**Pull request by krekas**

### CODE REVIEW

**Comment by ousid** [comment]
Thanks, @krekas, for your PR.

Can you update the README file, with the new `assignTo` method?

**Comment by krekas** [comment]
@ousid updated

**Comment by ousid** [comment]
> @ousid updated

Thanks! Can you please take a look at the reviewed parts?

**Comment by krekas** [comment]
@ousid don't see any reviews you posted

**Review by ousid — CHANGES_REQUESTED** [review]

**Comment by krekas** [comment]
@ousid made changes.

**Review by ousid — APPROVED** [review]

**Comment by ousid** [comment]
Thanks, @krekas!!

**Pull request merged**
